 Create two 3×3 matrices using the random function in Numpy and perform the following operations.

In [22]:
import numpy as np

m1 = np.random.rand(3, 3)
m2 = np.random.rand(3, 3)

dot = np.dot(m1, m2)
mul = np.matmul(m1, m2)
pro = np.multiply(m1, m2)  

print("Matrix 1:")
print(m1)
print()
print("Matrix 2:")
print(m2)
print()
print("Dot product:")
print(dot)
print()
print("Matrix multiplication:")
print(mul)
print()
print("Element-wise product:")  
print(pro)


Matrix 1:
[[8.97100598e-04 5.86339271e-01 1.28607651e-01]
 [9.03334763e-01 6.39769682e-01 3.61980319e-01]
 [3.31281037e-01 4.41492531e-01 5.55913934e-01]]

Matrix 2:
[[0.93335269 0.8735558  0.02649619]
 [0.52337496 0.71446371 0.08262018]
 [0.98728076 0.88506032 0.54641086]]

Dot product:
[[0.43468446 0.53352733 0.11873984]
 [1.53534556 1.56657996 0.27458279]
 [1.08911131 1.09684023 0.34901129]]

Matrix multiplication:
[[0.43468446 0.53352733 0.11873984]
 [1.53534556 1.56657996 0.27458279]
 [1.08911131 1.09684023 0.34901129]]

Element-wise product:
[[0.00083731 0.51220007 0.00340761]
 [0.4727828  0.45709222 0.02990688]
 [0.32706739 0.39074752 0.30375741]]


Perform the following set operations using the Numpy functions.
-Union
-Intersection
-Set Difference
-XOR

In [12]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([20, 40, 60, 80])

print("Union of two arrays :", np.union1d(arr1, arr2))
print("Intersection of two arrays :", np.intersect1d(arr1, arr2))
print("Set difference of two arrays :", np.setdiff1d(arr1, arr2))
print("XOR of two arrays :", np.bitwise_xor(arr1, arr2))

Union of two arrays : [10 20 30 40 60 80]
Intersection of two arrays : [20 40]
Set difference of two arrays : [10 30]
XOR of two arrays : [ 30  60  34 120]


 Create a 1D array using Random function and perform the following operations.
 -Cumulative sum
 -Cumulative Product
 -Discrete difference (with n=3)
 -Find the unique elements from the array

In [44]:
arr1d = np.random.randint(10, size=10)
print(arr1d)
sum = 0
product = 1
for i in range(0,len(arr1d)):
    sum = sum+arr1d[i]
    product = product*arr1d[1]
print("\nCumulative sum: ",sum)
print("\nCumulative product: ",product)
diff = np.diff(arr1d, n=3)
print("\nDiscrete Difference (n=3):", diff)
unique_elements = np.unique(diff)
print("\nUnique Elements in the Difference Array:", unique_elements)

[2 5 2 2 9 6 5 5 2 3]

Cumulative sum:  41

Cumulative product:  9765625

Discrete Difference (n=3): [  9   4 -17  12  -1  -4   7]

Unique Elements in the Difference Array: [-17  -4  -1   4   7   9  12]


 Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [48]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
print("Array 1:", array1)
print("Array 2:", array2)

def add_elements(x, y):
    print("Addition using user-defined function (frompyfunc()):", x+y)
add_elements(array1,array2)

result_zip = [x + y for x, y in zip(array1, array2)]
print("Addition using zip():", result_zip)

result_np_add = np.add(array1, array2)
print("Addition using np.add():", result_np_add)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Addition using user-defined function (frompyfunc()): [ 7  9 11 13 15]
Addition using zip(): [7, 9, 11, 13, 15]
Addition using np.add(): [ 7  9 11 13 15]


Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [45]:
from functools import reduce
from math import gcd

def lcm(x, y):
    return x * y // gcd(x, y)

def gcd_reduce(arr):
    return reduce(gcd, arr)

elements = np.array([12, 18, 24, 36])
lcm_result = reduce(lcm, elements)
gcd_result = gcd_reduce(elements)

print("Array of Elements:", elements)
print("LCM of the Elements:", lcm_result)
print("GCD of the Elements:", gcd_result)

Array of Elements: [12 18 24 36]
LCM of the Elements: 72
GCD of the Elements: 6
