In [1]:
import numpy as np

Write a program to distinguish between Array Indexing and Fancy Indexing.

In [4]:

arr=np.array([4,5,7,1,2])
print("Array Indexing: ",arr[4])
selected_index = arr[[0,2,3]]
print("Fancy indexing: ",selected_index)

Array Indexing:  2
Fancy indexing:  [4 7 1]


Execute the 2D array Slicing.

In [17]:
arr2d = np.array([[4,4,4],[5,5,5],[6,6,6]])
print("\n2D Array\n")
print(arr2d)
print("\nSlicing\n")
print("First Row: ",arr2d[0])
print("last row: ",arr2d[-1])
print("First row first two element: ",arr2d[0][0:2])
print("Third row last element: ",arr2d[2][-1])


2D Array

[[4 4 4]
 [5 5 5]
 [6 6 6]]

Slicing

First Row:  [4 4 4]
last row:  [6 6 6]
First row first two element:  [4 4]
Third row last element:  6


Create the 5-Dimensional arrays using ‘ndmin’.

In [18]:
import numpy as np
a = np.array([1, 2, 3, 4, 5], ndmin=5)
print(a)

[[[[[1 2 3 4 5]]]]]


Reshape the array from 1-D to 2-D array.

In [21]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print("\n1D-array\n")
print(a)
print("\n2x3-matrix\n")
b = a.reshape(2, 3)
print(b)


1D-array

[1 2 3 4 5 6]

2x3-matrix

[[1 2 3]
 [4 5 6]]


Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [1]:
import numpy as np


arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked_arr = np.stack((arr1, arr2), axis=0)
hstacked_arr = np.hstack((arr1, arr2))
vstacked_arr = np.vstack((arr1, arr2))
dstacked_arr = np.dstack((arr1, arr2))
print("Stacked: \n",stacked_arr)
print("hStacked: \n",hstacked_arr)
print("vStacked: \n",vstacked_arr)
print("dStacked: \n",dstacked_arr)


Stacked: 
 [[1 2 3]
 [4 5 6]]
hStacked: 
 [1 2 3 4 5 6]
vStacked: 
 [[1 2 3]
 [4 5 6]]
dStacked: 
 [[[1 4]
  [2 5]
  [3 6]]]


Perform the searchsort method in Numpy array.

In [8]:
sorted_arr = np.array([2, 4, 6, 8, 10])
n = int(input("Enter the element tobe searched: "))
index_to_insert = np.searchsorted(sorted_arr, n)

print(f"Value {n} should be inserted at index {index_to_insert} to maintain the sorted order.")


Value 4 should be inserted at index 1 to maintain the sorted order.


Create Numpy Structured array using your domain features.

In [12]:
faculty_dtype = np.dtype([
    ('name', 'U30'),         
    ('department', 'U30'),  
    ('salary', float),       
    ('experience_years', int) 
])

faculty_data = np.array([], dtype=faculty_dtype)

faculty_data = np.append(faculty_data, np.array([('John Doe', 'Computer Science', 75000.00, 5)], dtype=faculty_dtype))
faculty_data = np.append(faculty_data, np.array([('Jane Smith', 'Mathematics', 68000.00, 8)], dtype=faculty_dtype))
faculty_data = np.append(faculty_data, np.array([('Alice Johnson', 'Physics', 82000.00, 10)], dtype=faculty_dtype))
faculty_data = np.append(faculty_data, np.array([('Bob Wilson', 'Chemistry', 70000.00, 7)], dtype=faculty_dtype))

print(faculty_data)


[('John Doe', 'Computer Science', 75000.,  5)
 ('Jane Smith', 'Mathematics', 68000.,  8)
 ('Alice Johnson', 'Physics', 82000., 10)
 ('Bob Wilson', 'Chemistry', 70000.,  7)]


Create Data frame using List and Dictionary.

In [2]:
import pandas as pd

In [14]:
data = {
    'Name': ['John', 'Alice', 'Bob', 'Eve'],
    'Age': [28, 24, 32, 30],
    'Department': ['HR', 'IT', 'Finance', 'Marketing']
}

df_from_dict = pd.DataFrame(data)

print("DataFrame created from dictionary:")
print(df_from_dict)

names = ['John', 'Alice', 'Bob', 'Eve']
ages = [28, 24, 32, 30]
departments = ['HR', 'IT', 'Finance', 'Marketing']

data_from_lists = {
    'Name': names,
    'Age': ages,
    'Department': departments
}

df_from_lists = pd.DataFrame(data_from_lists)


print("\nDataFrame created from lists and a dictionary:")
print(df_from_lists)


DataFrame created from dictionary:
    Name  Age Department
0   John   28         HR
1  Alice   24         IT
2    Bob   32    Finance
3    Eve   30  Marketing

DataFrame created from lists and a dictionary:
    Name  Age Department
0   John   28         HR
1  Alice   24         IT
2    Bob   32    Finance
3    Eve   30  Marketing


Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
  
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [16]:
file = pd.read_csv("D:\christ\sem 1\python programming\juptyer-notebook\csv\sample_faculty.csv")
df = pd.DataFrame(file)
df.info()

df['Salary_paid'] = pd.to_numeric(df['Salary_paid'], errors='coerce')

print("check for missing values using isnull()")
print(df.isnull())

print("check for non-missing values using isnull()")
print(df.notnull())

print("Data Frame after using dropna")
print(df.dropna())

mean_quantity = df['Salary_paid'].mean()
df_filled = df.fillna({'Salary_paid': mean_quantity})
print("\nDataFrame after filling missing quantity values:")
print(df_filled)

df_replaced = df.replace({'Given name': {'STACEY': 'GEWN'}})
print("\nDataFrame after replacing 'STACEY' with 'GEWN':")
print(df_replaced)

df_interpolated = df.interpolate()
print("\nDataFrame after linear interpolation")
print(df_interpolated)



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Given_name      49 non-null     object
 1   Position_title  48 non-null     object
 2   Salary_paid     48 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB
check for missing values using isnull()
    Given_name  Position_title  Salary_paid
0        False           False         True
1        False           False         True
2        False           False         True
3        False           False         True
4        False           False         True
5        False           False         True
6        False           False         True
7        False           False         True
8        False           False         True
9        False           False         True
10       False           False         True
11       False           False         True
12       False           F

Perform the Hierarchical Indexing in the above created dataset.

In [17]:
df.set_index(['Given_name', 'Position_title'], inplace=True)

# Print the DataFrame with the new index
print("\nDataFrame with 'Given name' and 'Position title' as index:")
print(df)


DataFrame with 'Given name' and 'Position title' as index:
                                                               Salary_paid
Given_name Position_title                                                 
YOUSRA     Assistant Professor                                         NaN
EIHAB      Professor                                                   NaN
ISHAN S.   Associate Director, Systems                                 NaN
HOSSEIN    Associate Professor                                         NaN
JOHN       Academic Dean, Continuing Lecturer, and Manager...          NaN
NASSER M.  Associate Professor                                         NaN
HECTOR     Sessional Instructor                                        NaN
KATHERINE  Professor                                                   NaN
STACEY     Associate Professor                                         NaN
WENDI L.   Professor                                                   NaN
JAMES      Lecturer                     